name: crafter_env
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - icu=75.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=20.1.8
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.5.3
  - pip=25.2
  - psutil=7.0.0
  - python=3.10.18
  - python_abi=3.10
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - pip:
      - filelock==3.19.1
      - fsspec==2025.9.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - sympy==1.14.0
      - torch==2.8.0
      - typing-extensions==4.15.0